# Step 1: run tests and build über jar
FROM maven:3.8-eclipse-temurin-11-alpine as build

# declarar variables de entorno
ARG github_actor
ARG github_token
ENV GITHUB_ACTOR=$github_actor
ENV GITHUB_TOKEN=$github_token

WORKDIR /build

# Repositorio local
COPY local-maven-repo /local-maven-repo

# Cache Maven dependencies
COPY cms-nuxeo-service/pom.xml .
COPY cms-nuxeo-service/settings.xml .
RUN mvn -e -s settings.xml dependency:go-offline

# Cache Maven dependencies
#COPY ../pom.xml .
#RUN mvn dependency:go-offline

# Build project
COPY cms-nuxeo-service/src ./src/
RUN mvn -e -s settings.xml package -DskipTests


# Step 2: package über jar
FROM eclipse-temurin:11-jre-alpine
LABEL maintainer="avirgili@eclub.com.py"

# Create system user
RUN apk add --no-cache alpine-conf \
    && setup-timezone -z America/Asuncion \
    && addgroup --system spring --gid 1000 \
    && adduser --system spring --uid 1000 --ingroup spring
USER spring:spring

WORKDIR /home/spring
COPY --from=build --chown=spring:spring build/target/*.jar ./app.jar
CMD ["java", "-jar", "app.jar"]