version: "3"
services:
  postgres:
    image: postgres:12.9-alpine
    hostname: postgres
    restart: unless-stopped
    networks:
      - eclub
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/postgresql:/var/lib/postgresql/data
    env_file:
      - .env
  app:
    hostname: app
    depends_on:
      - postgres
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - eclub
    ports:
      - "8443:8443"
    env_file:
      - .env
networks:
  eclub:
