version: "3"
services:
  app:
    hostname: app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-nuxeo
    networks:
      - eclub
    ports:
      - "8443:8443"
    env_file:
      - .env
networks:
  eclub:
