server:
  port: ${SERVER_PORT}
debug:  ${DEBUG_ON:false}
logging:
  level:
    root: ${LEVEL_ROOT:INFO}
nuxeo:
  api:
    url: ${NUXEO_API_URL}
    username: ${NUXEO_USER}
    password: ${NUXEO_PASS}
configuracion:
  ambiente: ${ENVIRONMENT:development} #${ENVIRONMENT}
spring:
  output:
    ansi:
      enabled: always
  application:
    name: ${APP_NAME:nuxeo-manager-service} #${APP_NAME}
  servlet:
    multipart:
      enabled: ${MULTIPART_ENABLED:true} # Whether to enable support of multipart uploads.
      #file-size-threshold: 0  Threshold after which files are written to disk. Values can use the suffixes "MB" or "KB" to indicate megabytes or kilobytes, respectively.
      max-file-size: ${MAX_FILE:3MB} # Max file size. Values can use the suffixes "MB" or "KB" to indicate megabytes or kilobytes, respectively.
      max-request-size: ${MAX_REQUEST:12MB} # Max request size. Values can use the suffixes "MB" or "KB" to indicate megabytes or kilobytes, respectively.
      #resolve-lazily: false  Whether to resolve the multipart request lazily at the time of file or parameter access.
springdoc:
  packagesToScan: eclub.com.cmsnuxeo
  pathsToMatch: /api/v1/nuxeo, /v1, /api/v1/**