server:
  port: 8000
debug: true
logging:
  level:
    root: INFO
nuxeo:
  api:
    url: http://10.30.0.51:8080/api/v1/
    username: Administrator
    password: Administrator
configuracion:
  ambiente: development
spring:
  application:
    name: nuxeo-manager-service
