server:
  port: 8000
debug: true
logging:
  level:
    root: INFO
nuxeo:
  api:
    url: http://10.30.0.51:8080/nuxeo/api/v1
    username: Administrator
    password: Administrator
configuracion:
  ambiente: development
spring:
  application:
    name: nuxeo-manager-service
  servlet:
    multipart:
      enabled: true # Whether to enable support of multipart uploads.
      #file-size-threshold: 0  Threshold after which files are written to disk. Values can use the suffixes "MB" or "KB" to indicate megabytes or kilobytes, respectively.
      max-file-size: 3MB # Max file size. Values can use the suffixes "MB" or "KB" to indicate megabytes or kilobytes, respectively.
      max-request-size: 10MB # Max request size. Values can use the suffixes "MB" or "KB" to indicate megabytes or kilobytes, respectively.
      #resolve-lazily: false  Whether to resolve the multipart request lazily at the time of file or parameter access.
